### ISSUE TITLE
error when open javafx app.

### ISSUE THREAD

**Issue by parasuraam** [beryx-gist/badass-runtime-example-javafx#29] opened 2020-11-19 10:18 UTC
![erjp](https://user-images.githubusercontent.com/67687893/99652701-100d7600-2a50-11eb-9b53-3f3438837131.PNG)

I download installer from https://github.com/beryx-gist/badass-runtime-example-javafx/actions/runs/371006927  .

after I install , it comes an error like this
 
[hs_err_pid4540.log](https://github.com/beryx-gist/badass-runtime-example-javafx/files/5566039/hs_err_pid4540.log)

**Comment by Srijan-Sengupta** [comment] 2020-11-19 12:47
Hey @parasuraam is it 32-bit OS running in some VM?

**Comment by parasuraam** [comment] 2020-11-19 13:07
I am using windows 64 bit  .

**Comment by siordache** [comment] 2020-11-19 13:36
The error seems to be caused by [this bug](https://bugs.openjdk.java.net/browse/JDK-8254920).

The bug is fixed in JDK 16, but Gradle doesn't support it yet. That's why I cannot configure the GitHub Action to build the installer with Java 16.

**Comment by Srijan-Sengupta** [comment] 2020-11-19 13:44
Yes @siordache you are correct!

**Closed** 2020-11-19 14:17 UTC
